export const GET_CELEBS_RESPONSE = 'GET_CELEBS_RESPONSE';
export const GET_CELEB_RESPONSE = 'GET_CELEB_RESPONSE';
export const ADD_NEW_CELEB_RESPONSE = 'ADD_NEW_CELEB_RESPONSE';
export const DELETE_CELEB_RESPONSE = 'DELETE_CELEB_RESPONSE';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
